"""Emit C++ econ test vectors for src/test/storage_econ_vectors.h (§114)."""
import random
import sys

sys.path.insert(0, "contrib/quantbtc/ref")
from storage_econ import (MAX_MONEY, STATUS_ACTIVE, STATUS_EXITED,
                          STATUS_SUSPENDED, calc_reward, encode_record)

rng = random.Random(0xEC00 + 1)
rewards = []
# hand-picked limb-stress + floor edges
fixed = [
    (2**40, 10**6, 2**40),
    (2**64 - 1, 21 * 10**14, 2**64 - 1),
    (2**64 - 1, 0, 2**64 - 1),
    (100, 1, 99),
    (2**30, 7, 2**30 - 1),
    (1, 1, 1),
    (2**64 - 1, 2**64 - 1, 0),   # verified=0, huge price (price invalid in C++? price>MAX -> INVALID)
    (2**63, 2**63 - 1, 2**63),   # max limb pressure, price invalid -> INVALID
    (MAX_MONEY * 2, 2**30, MAX_MONEY * 2),  # exact MAX overflow boundary probe
]
for _ in range(12):
    cap = rng.choice((rng.randrange(1, 2**64), 2**40, 2**30))
    price = rng.choice((0, 1, rng.randrange(1, 21 * 10**14 + 1)))
    ver = rng.randrange(0, min(cap, 2**40) + 1)
    fixed.append((cap, price, ver))
for cap, price, ver in fixed:
    amt, cls = calc_reward(cap, price, ver)
    rewards.append((cap, price, ver, -1 if amt is None else amt, cls))

records = []
for slen, status in ((1, STATUS_ACTIVE), (25, STATUS_SUSPENDED),
                     (10000, STATUS_EXITED), (300, STATUS_ACTIVE)):
    pid = bytes(rng.randrange(256) for _ in range(32))
    script = bytes(rng.randrange(256) for _ in range(slen))
    cap = rng.choice((1, 2**40, 2**64 - 1))
    price = rng.choice((0, 1, 21 * 10**14))
    epoch = rng.choice((0, 7, 2**64 - 1))
    blob = encode_record(pid, script, cap, price, status, epoch)
    records.append((pid.hex(), script.hex(), cap, price, status, epoch, blob.hex()))

L = []
A = L.append
A("// Auto-generated by contrib/quantbtc/gen_storage_econ_vectors.py — DO NOT EDIT.")
A("#ifndef BITCOIN_TEST_STORAGE_ECON_VECTORS_H")
A("#define BITCOIN_TEST_STORAGE_ECON_VECTORS_H")
A("")
A("#include <cstdint>")
A("#include <string>")
A("#include <vector>")
A("")
A("struct StorageRewardVector {")
A("    uint64_t capacity, price, verified;")
A("    int64_t amount; // -1 iff not OK")
A("    int cls; // 0=OK 1=OVERFLOW 2=INVALID_INPUT")
A("};")
A("")
A("static const std::vector<StorageRewardVector> STORAGE_REWARD_VECTORS = {")
for cap, price, ver, amt, cls in rewards:
    code = {"OK": 0, "OVERFLOW": 1, "INVALID_INPUT": 2}[cls]
    A("    {%dULL, %dULL, %dULL, %dLL, %d}," % (cap, price, ver, amt, code))
A("};")
A("")
A("struct StorageRecordVector {")
A("    std::string pid_hex, script_hex, blob_hex;")
A("    uint64_t capacity, price, epoch;")
A("    int status;")
A("};")
A("")
A("static const std::vector<StorageRecordVector> STORAGE_RECORD_VECTORS = {")
for pid, script, cap, price, status, epoch, blob in records:
    A('    {"%s", "%s", "%s", %dULL, %dULL, %dULL, %d},' % (
        pid, script, blob, cap, price, epoch, status))
A("};")
A("")
A("#endif // BITCOIN_TEST_STORAGE_ECON_VECTORS_H")
A("")
open("src/test/storage_econ_vectors.h", "w").write("\n".join(L))
print("wrote %d reward + %d record vectors" % (len(rewards), len(records)))
