"""Emit C++ NFT test vectors for src/test/nft_vectors.h (§114)."""
import random
import sys

sys.path.insert(0, "contrib/quantbtc/ref")
from nft_record import encode_mint, nft_id

rng = random.Random(0x9713 + 1)
cases = []
cid = bytes(rng.randrange(256) for _ in range(32))
for slen, serial, epoch in ((1, 0, 0), (25, 7, 7),
                            (10000, 2**64 - 1, 2**64 - 1), (300, 42, 100)):
    root = bytes(rng.randrange(256) for _ in range(32))
    meta = bytes(rng.randrange(256) for _ in range(32))
    script = bytes(rng.randrange(256) for _ in range(slen))
    blob = encode_mint(cid, serial, root, meta, script, epoch)
    cases.append((cid.hex(), serial, root.hex(), meta.hex(), script.hex(),
                  epoch, blob.hex(), nft_id(cid, serial).hex()))

L = []
A = L.append
A("// Auto-generated by contrib/quantbtc/gen_nft_vectors.py — DO NOT EDIT.")
A("#ifndef BITCOIN_TEST_NFT_VECTORS_H")
A("#define BITCOIN_TEST_NFT_VECTORS_H")
A("")
A("#include <cstdint>")
A("#include <string>")
A("#include <vector>")
A("")
A("struct NftVector {")
A("    std::string cid_hex, root_hex, meta_hex, script_hex, blob_hex, id_hex;")
A("    uint64_t serial, epoch;")
A("};")
A("")
A("static const std::vector<NftVector> NFT_VECTORS = {")
for cid_h, serial, root, meta, script, epoch, blob, nid in cases:
    A('    {"%s", "%s", "%s", "%s", "%s", "%s", %dULL, %dULL},' % (
        cid_h, root, meta, script, blob, nid, serial, epoch))
A("};")
A("")
A("#endif // BITCOIN_TEST_NFT_VECTORS_H")
A("")
open("src/test/nft_vectors.h", "w").write("\n".join(L))
print("wrote %d nft vectors" % len(cases))
