"""Emit C++ test vectors for src/test/storage_test_vectors.h (§114)."""
import random
import sys

sys.path.insert(0, "contrib/quantbtc/ref")
from storage_proof import (chunkify, content_commit, derive_indices,
                           encode_proof, prove, sha256d)

rng = random.Random(0x5702A6E + 1)
cases = []
sizes = (1, 3 * 65536 + 17, 100000)
for ci, size in enumerate(sizes):
    data = bytes(rng.randrange(256) for _ in range(size))
    hashes, root = content_commit(data)
    chunks = chunkify(data)
    pid = sha256d(b"storage-test-provider-%d" % ci)
    epoch = (0, 7, 2**64 - 1)[ci]
    idxs = derive_indices(root, pid, epoch, len(chunks))
    pr = prove(chunks, idxs[0])
    cases.append((data, hashes, root, pid, epoch, idxs, pr))

L = []
A = L.append
A("// Auto-generated by contrib/quantbtc/gen_storage_vectors.py — DO NOT EDIT.")
A("// Differential vectors: Python ref (storage_proof.py) -> C++ (src/storage).")
A("#ifndef BITCOIN_TEST_STORAGE_TEST_VECTORS_H")
A("#define BITCOIN_TEST_STORAGE_TEST_VECTORS_H")
A("")
A("#include <cstdint>")
A("#include <string>")
A("#include <vector>")
A("")
A("struct StorageTestVector {")
A("    std::string content_hex;")
A("    std::string root_hex;")
A("    std::string provider_hex;")
A("    uint64_t epoch;")
A("    std::vector<uint32_t> indices;")
A("    uint32_t proof_index;")
A("    std::string chunk_hex;")
A("    std::vector<std::string> path_hex;")
A("    std::string envelope_hex;")
A("};")
A("")
A("static const std::vector<StorageTestVector> STORAGE_TEST_VECTORS = {")
for data, hashes, root, pid, epoch, idxs, pr in cases:
    A("    {")
    A('        "%s",' % data.hex())
    A('        "%s",' % root.hex())
    A('        "%s",' % pid.hex())
    A("        %dULL," % epoch)
    A("        {%s}," % ", ".join("%du" % i for i in idxs))
    A("        %du," % pr["index"])
    A('        "%s",' % bytes(pr["chunk"]).hex())
    A("        {%s}," % ", ".join('"%s"' % bytes(s).hex() for s in pr["path"]))
    A('        "%s",' % encode_proof(pr).hex())
    A("    },")
A("};")
A("")
A("#endif // BITCOIN_TEST_STORAGE_TEST_VECTORS_H")
A("")
open("src/test/storage_test_vectors.h", "w").write("\n".join(L))
print("wrote %d vectors" % len(cases))
